Name: admin
Host: 0.0.0.0
Port: 8888
Log:
  Mode: console
Timeout: 1500
HashSalt: MTF)kaA}.5x85SK~J{6gf88_jc;?RH<+
Auth:
  AccessSecret: YhCRfmTatNG9c8mQkrkazYjd5B2QNQXB
  AccessExpire: 1612867074
CartRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: cart.rpc
CatalogRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: catalog.rpc
CustomerRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: customer.rpc
EmailRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: email.rpc
InventoryRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: inventory.rpc
OthersBoughtRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: othersbought.rpc
PaymentRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: payment.rpc
ShippingRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: shipping.rpc
SimilarProductsRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: similarproducts.rpc
StoreRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: store.rpc
UserRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: user.rpc
WarehouseRpc:
  Etcd:
    Hosts:
      - etcd-client:2379
    Key: warehouse.rpc
