name: e2e

on:
  push:
    branches: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - name: Install Flux in Kubernetes Kind
        run: flux install --log-level debug
      - name: Setup cluster reconciliation
        run: |
          flux create source git flux-system \
          --interval=15m \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/}
          flux create kustomization flux-system \
          --interval=15m \
          --source=flux-system \
          --path=./clusters/staging
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
          kubectl -n flux-system wait kustomization/kyverno-policies --for=condition=ready --timeout=1m
          kubectl -n flux-system wait kustomization/tenants --for=condition=ready --timeout=3m
      - name: Verify tenant reconciliation
        run: |
          kubectl -n apps wait kustomization/dev-team --for=condition=ready --timeout=1m
          kubectl -n apps wait helmrelease/podinfo --for=condition=ready --timeout=1m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          kubectl -n flux-system logs deploy/notification-controller
          kubectl -n kyverno get all
          kubectl -n kyverno logs deploy/kyverno
          kubectl get clusterpolicy flux-multi-tenancy -oyaml
          flux get sources all --all-namespaces
          flux get ks --all-namespaces

