// Code generated by goctl. DO NOT EDIT.
package types

type Product struct {
	Id               int64     `json:"id,omitempty"`
	Slug             string    `json:"slug,omitempty"`
	Name             string    `json:"name,omitempty"`
	ShortDescription string    `json:"shortDescription,omitempty"`
	Description      string    `json:"description,omitempty"`
	MetaTitle        string    `json:"metaTitle,omitempty"`
	MetaDescription  string    `json:"metaDescription,omitempty"`
	MetaKeywords     string    `json:"metaKeywords,omitempty"`
	Promotionable    bool      `json:"promotionable,omitempty"`
	AvailableOn      string    `json:"availableOn,omitempty"`
	DiscontinueOn    string    `json:"discontinueOn,omitempty"`
	Variants         []Variant `json:"variants,omitempty"`
}

type Variant struct {
	Id                 int64   `json:"id,omitempty"`
	ProductId          int64   `json:"productId,omitempty"`
	IsDefault          bool    `json:"isDefault,omitempty"`
	Sku                string  `json:"sku,omitempty"`
	SortOrder          int32   `json:"sortOrder,omitempty"`
	CostAmount         float64 `json:"costAmount,omitempty"`
	CostCurrency       string  `json:"costCurrency,omitempty"`
	TrackInventory     bool    `json:"trackInventory,omitempty"`
	TaxCategoryId      int64   `json:"taxCategoryId,omitempty"`
	ShippingCategoryId int64   `json:"shippingCategoryId,omitempty"`
	DiscontinueOn      string  `json:"discontinueOn,omitempty"`
	Weight             float64 `json:"weight,omitempty"`
	Height             float64 `json:"height,omitempty"`
	Width              float64 `json:"width,omitempty"`
	Depth              float64 `json:"depth,omitempty"`
}

type GetProductBySkuRequest struct {
	Sku string `path:"sku"`
}

type GetProductBySlugRequest struct {
	Slug string `path:"slug"`
}

type GetProductByIdRequest struct {
	Id int64 `path:"id"`
}

type GetProductsByCategoryIdRequest struct {
	CategoryId  int64  `path:"categoryId"`
	CurrentPage int64  `path:"currentPage"`
	PageSize    int64  `path:"pageSize"`
	SortOn      string `form:"sortOn,optional"`
}

type GetProductsByCategoryIdResponse struct {
	Products     []Product `json:"products"`
	TotalRecords int64     `json:"totalRecords"`
	TotalPages   int64     `json:"totalPages"`
}

type GetAllProductsRequest struct {
	CurrentPage int64  `path:"currentPage"`
	PageSize    int64  `path:"pageSize"`
	SortOn      string `form:"sortOn"`
}

type GetAllProductsResponse struct {
	Products     []Product `json:"products"`
	TotalRecords int64     `json:"totalRecords"`
	TotalPages   int64     `json:"totalPages"`
}
