FROM golang:alpine

COPY . /app
# COPY ./services /app/services
# COPY ./internal /app/internal
# COPY ./env /app/env

RUN cd /app && go mod tidy

# RUN go get github.com/cespare/reflex
# COPY reflex.conf /
# COPY . /app
# ENTRYPOINT ["reflex", "-c", "/reflex.conf"]