Name: payment.rpc
ListenOn: 0.0.0.0:8080
Log:
  Mode: console
Etcd:
  Hosts:
    - etcd-client:2379
  Key: payment.rpc
PostgresConfig:
  Connection: postgres://postgres:postgres@k8scommerce-db:5432/k8scommerce?connect_timeout=180&sslmode=disable
  MaxOpenConnections: 10
  MaxIdleConnections: 2
  MaxConnectionLifetimeMinutes: 5