// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package othersbought

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OthersBoughtClientClient is the client API for OthersBoughtClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OthersBoughtClientClient interface {
	GetOthersBoughtBySku(ctx context.Context, in *GetOthersBoughtBySkuRequest, opts ...grpc.CallOption) (*GetOthersBoughtBySkuResponse, error)
}

type othersBoughtClientClient struct {
	cc grpc.ClientConnInterface
}

func NewOthersBoughtClientClient(cc grpc.ClientConnInterface) OthersBoughtClientClient {
	return &othersBoughtClientClient{cc}
}

func (c *othersBoughtClientClient) GetOthersBoughtBySku(ctx context.Context, in *GetOthersBoughtBySkuRequest, opts ...grpc.CallOption) (*GetOthersBoughtBySkuResponse, error) {
	out := new(GetOthersBoughtBySkuResponse)
	err := c.cc.Invoke(ctx, "/othersbought.OthersBoughtClient/GetOthersBoughtBySku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OthersBoughtClientServer is the server API for OthersBoughtClient service.
// All implementations must embed UnimplementedOthersBoughtClientServer
// for forward compatibility
type OthersBoughtClientServer interface {
	GetOthersBoughtBySku(context.Context, *GetOthersBoughtBySkuRequest) (*GetOthersBoughtBySkuResponse, error)
	mustEmbedUnimplementedOthersBoughtClientServer()
}

// UnimplementedOthersBoughtClientServer must be embedded to have forward compatible implementations.
type UnimplementedOthersBoughtClientServer struct {
}

func (UnimplementedOthersBoughtClientServer) GetOthersBoughtBySku(context.Context, *GetOthersBoughtBySkuRequest) (*GetOthersBoughtBySkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOthersBoughtBySku not implemented")
}
func (UnimplementedOthersBoughtClientServer) mustEmbedUnimplementedOthersBoughtClientServer() {}

// UnsafeOthersBoughtClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OthersBoughtClientServer will
// result in compilation errors.
type UnsafeOthersBoughtClientServer interface {
	mustEmbedUnimplementedOthersBoughtClientServer()
}

func RegisterOthersBoughtClientServer(s grpc.ServiceRegistrar, srv OthersBoughtClientServer) {
	s.RegisterService(&OthersBoughtClient_ServiceDesc, srv)
}

func _OthersBoughtClient_GetOthersBoughtBySku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOthersBoughtBySkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OthersBoughtClientServer).GetOthersBoughtBySku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/othersbought.OthersBoughtClient/GetOthersBoughtBySku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OthersBoughtClientServer).GetOthersBoughtBySku(ctx, req.(*GetOthersBoughtBySkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OthersBoughtClient_ServiceDesc is the grpc.ServiceDesc for OthersBoughtClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OthersBoughtClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "othersbought.OthersBoughtClient",
	HandlerType: (*OthersBoughtClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOthersBoughtBySku",
			Handler:    _OthersBoughtClient_GetOthersBoughtBySku_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "othersbought.proto",
}
