apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - daemonset.yaml
  - deployment.yaml
  - pvc.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: prometheus-nab-giftcard-server
    files:
      - config/alerting_rules.yml
      - config/alerts
      - config/prometheus.yml
      - config/recording_rules.yml
      - config/rules
  - name: prometheus-nab-giftcard-alertmanager
    files:
      - config/alertmanager.yml
patchesStrategicMerge:
  - patch/cm-server.yaml
  - patch/cm-alertmanager.yaml