---
# Source: prometheus/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: prometheus-nab-giftcard
  name: prometheus-nab-giftcard-kube-state-metrics
  namespace: default
imagePullSecrets:
  []
---
# Source: prometheus/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: prometheus-nab-giftcard
  name: prometheus-nab-giftcard-alertmanager
  namespace: default
  annotations:
    {}
---
# Source: prometheus/templates/node-exporter/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: prometheus-nab-giftcard
  name: prometheus-nab-giftcard-node-exporter
  namespace: default
  annotations:
    {}
---
# Source: prometheus/templates/pushgateway/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: prometheus-nab-giftcard
  name: prometheus-nab-giftcard-pushgateway
  namespace: default
  annotations:
    {}
---
# Source: prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus-nab-giftcard
  name: prometheus-nab-giftcard-server
  namespace: default
  annotations:
    {}