// Code generated by goctl. DO NOT EDIT!
// Source: store.proto

package server

import (
	"context"

	"github.com/k8scommerce/k8scommerce/services/rpc/client/internal/logic"
	"github.com/k8scommerce/k8scommerce/services/rpc/client/internal/svc"
	"github.com/k8scommerce/k8scommerce/services/rpc/client/pb/store"

	"github.com/localrivet/galaxycache"
)

type StoreClientServer struct {
	svcCtx   *svc.ServiceContext
	universe *galaxycache.Universe
}

func NewStoreClientServer(svcCtx *svc.ServiceContext, universe *galaxycache.Universe) *StoreClientServer {
	return &StoreClientServer{
		svcCtx:   svcCtx,
		universe: universe,
	}
}

func (s *StoreClientServer) CreateStore(ctx context.Context, in *store.CreateStoreRequest) (*store.CreateStoreResponse, error) {
	l := logic.NewCreateStoreLogic(ctx, s.svcCtx, s.universe)
	return l.CreateStore(in)
}

func (s *StoreClientServer) GetStoreById(ctx context.Context, in *store.GetStoreByIdRequest) (*store.GetStoreByIdResponse, error) {
	l := logic.NewGetStoreByIdLogic(ctx, s.svcCtx, s.universe)
	return l.GetStoreById(in)
}

func (s *StoreClientServer) GetAllStores(ctx context.Context, in *store.GetAllStoresRequest) (*store.GetAllStoresResponse, error) {
	l := logic.NewGetAllStoresLogic(ctx, s.svcCtx, s.universe)
	return l.GetAllStores(in)
}
