// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"k8scommerce/services/api/client/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Locale, serverCtx.StoreKey},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/v1/cart/:customerId",
					Handler: getCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/cart/:customerId",
					Handler: addItemToCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/cart/:customerId/:sku",
					Handler: updateCartItemQuantityHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/v1/cart/:customerId/:sku",
					Handler: removeCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/v1/cart/:customerId",
					Handler: clearCartHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Locale, serverCtx.StoreKey},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/v1/categories",
					Handler: getAllCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/category/slug/:slug",
					Handler: getCategoryBySlugHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/category/:id",
					Handler: getCategoryByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/product/sku/:sku",
					Handler: getProductBySkuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/product/slug/:slug",
					Handler: getProductBySlugHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/product/:id",
					Handler: getProductByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/products/category/:categoryId/:currentPage/:pageSize",
					Handler: getProductsByCategoryIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/products/:currentPage/:pageSize",
					Handler: getAllProductsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Locale, serverCtx.StoreKey},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/customer/login",
					Handler: loginHandler(serverCtx),
				},
			}...,
		),
	)
}
