// Code generated by goctl. DO NOT EDIT!
// Source: shipping.proto

package server

import (
	"context"

	"github.com/k8s-commerce/k8s-commerce/services/rpc/shipping/github.com/k8s-commerce/k8s-commerce/services/rpc/shipping"
	"github.com/k8s-commerce/k8s-commerce/services/rpc/shipping/internal/logic"
	"github.com/k8s-commerce/k8s-commerce/services/rpc/shipping/internal/svc"

	"github.com/localrivet/galaxycache"
)

type ShippingServer struct {
	svcCtx   *svc.ServiceContext
	universe *galaxycache.Universe
}

func NewShippingServer(svcCtx *svc.ServiceContext, universe *galaxycache.Universe) *ShippingServer {
	return &ShippingServer{
		svcCtx:   svcCtx,
		universe: universe,
	}
}

func (s *ShippingServer) GetQuote(ctx context.Context, in *shipping.GetQuoteRequest) (*shipping.GetQuoteResponse, error) {
	l := logic.NewGetQuoteLogic(ctx, s.svcCtx, s.universe)
	return l.GetQuote(in)
}
