// Code generated by goctl. DO NOT EDIT!
// Source: shipping.proto

package server

import (
	"context"

	"github.com/k8s-commerce/k8s-commerce/services/rpc/shipping/internal/logic"
	"github.com/k8s-commerce/k8s-commerce/services/rpc/shipping/internal/svc"
	"github.com/k8s-commerce/k8s-commerce/services/rpc/shipping/pb/shipping"

	"github.com/localrivet/galaxycache"
)

type ShippingClientServer struct {
	svcCtx   *svc.ServiceContext
	universe *galaxycache.Universe
}

func NewShippingClientServer(svcCtx *svc.ServiceContext, universe *galaxycache.Universe) *ShippingClientServer {
	return &ShippingClientServer{
		svcCtx:   svcCtx,
		universe: universe,
	}
}

func (s *ShippingClientServer) GetQuote(ctx context.Context, in *shipping.GetQuoteRequest) (*shipping.GetQuoteResponse, error) {
	l := logic.NewGetQuoteLogic(ctx, s.svcCtx, s.universe)
	return l.GetQuote(in)
}
