Name: cart.rpc
Target: k8s://k8scommerce/cart
ListenOn: 0.0.0.0:8080
Log:
  Mode: console
InventoryRpc:
  Target: k8s://k8scommerce/inventory
OthersBoughtRpc:
  Target: k8s://k8scommerce/othersbought
Postgres:
  Connection: postgres://postgres:postgres@k8scommerce-db:5432/k8scommerce?connect_timeout=180&sslmode=disable
  MaxOpenConnections: 10
  MaxIdleConnections: 2
  MaxConnectionLifetimeMinutes: 5