version: "3"
services:
  postgres:
    container_name: k8scommerce-db
    image: postgis/postgis:12-master
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - k8scommerce
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: k8scommerce
    volumes:
      - .data:/var/lib/postgresql/data
    restart: unless-stopped
  migrations:
    build: .
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: k8scommerce
      PGHOST: postgres
      PGSSLMODE: disable
    volumes:
      - ./migrations:/migrations
    networks:
      - k8scommerce
    command: [ "/wait-for-postgres.sh", "/run-migrations.sh" ]

  # https://www.pgadmin.org/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.4
    depends_on:
      - postgres
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: k8scommerce@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - k8scommerce
    restart: unless-stopped

networks:
  k8scommerce:
    driver: bridge
