// Code generated by goctl. DO NOT EDIT!
// Source: warehouse.proto

package server

import (
	"context"

	"warehouse/internal/logic"
	"warehouse/internal/svc"
	"warehouse/pb/warehouse"

	"github.com/localrivet/galaxycache"
)

type WarehouseClientServer struct {
	svcCtx   *svc.ServiceContext
	universe *galaxycache.Universe
}

func NewWarehouseClientServer(svcCtx *svc.ServiceContext, universe *galaxycache.Universe) *WarehouseClientServer {
	return &WarehouseClientServer{
		svcCtx:   svcCtx,
		universe: universe,
	}
}

func (s *WarehouseClientServer) CreateWarehouse(ctx context.Context, in *warehouse.CreateWarehouseRequest) (*warehouse.CreateWarehouseResponse, error) {
	l := logic.NewCreateWarehouseLogic(ctx, s.svcCtx, s.universe)
	return l.CreateWarehouse(in)
}

func (s *WarehouseClientServer) GetAllWarehousesByStoreId(ctx context.Context, in *warehouse.GetAllWarehousesByStoreIdRequest) (*warehouse.GetAllWarehousesByStoreIdResponse, error) {
	l := logic.NewGetAllWarehousesByStoreIdLogic(ctx, s.svcCtx, s.universe)
	return l.GetAllWarehousesByStoreId(in)
}

func (s *WarehouseClientServer) GetWarehouseById(ctx context.Context, in *warehouse.GetWarehouseByIdRequest) (*warehouse.GetWarehouseByIdResponse, error) {
	l := logic.NewGetWarehouseByIdLogic(ctx, s.svcCtx, s.universe)
	return l.GetWarehouseById(in)
}
