// Code generated by goctl. DO NOT EDIT!
// Source: inventory.proto

package server

import (
	"context"

	"github.com/k8scommerce/k8scommerce/services/rpc/inventory/internal/logic"
	"github.com/k8scommerce/k8scommerce/services/rpc/inventory/internal/svc"
	"github.com/k8scommerce/k8scommerce/services/rpc/inventory/pb/inventory"

	"github.com/localrivet/galaxycache"
)

type InventoryClientServer struct {
	svcCtx   *svc.ServiceContext
	universe *galaxycache.Universe
}

func NewInventoryClientServer(svcCtx *svc.ServiceContext, universe *galaxycache.Universe) *InventoryClientServer {
	return &InventoryClientServer{
		svcCtx:   svcCtx,
		universe: universe,
	}
}

func (s *InventoryClientServer) GetItemQuantity(ctx context.Context, in *inventory.GetItemQuantityRequest) (*inventory.GetItemQuantityResponse, error) {
	l := logic.NewGetItemQuantityLogic(ctx, s.svcCtx, s.universe)
	return l.GetItemQuantity(in)
}
