// Code generated by goctl. DO NOT EDIT!
// Source: inventory.proto

package server

import (
	"context"

	"github.com/k8scommerce/k8scommerce/services/rpc/inventory/internal/logic"
	"github.com/k8scommerce/k8scommerce/services/rpc/inventory/internal/svc"
	"github.com/k8scommerce/k8scommerce/services/rpc/inventory/pb/inventory"
)

type InventoryClientServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryClientServer
}

func NewInventoryClientServer(svcCtx *svc.ServiceContext) *InventoryClientServer {
	return &InventoryClientServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryClientServer) GetItemQuantity(ctx context.Context, in *inventory.GetItemQuantityRequest) (*inventory.GetItemQuantityResponse, error) {
	l := logic.NewGetItemQuantityLogic(ctx, s.svcCtx)
	return l.GetItemQuantity(in)
}

func (s *InventoryClientServer) GetItemsQuantity(ctx context.Context, in *inventory.GetItemsQuantityRequest) (*inventory.GetItemsQuantityResponse, error) {
	l := logic.NewGetItemsQuantityLogic(ctx, s.svcCtx)
	return l.GetItemsQuantity(in)
}
