// Code generated by goctl. DO NOT EDIT!
// Source: similarproducts.proto

package server

import (
	"context"

	"k8scommerce/services/rpc/similarproducts/internal/logic"
	"k8scommerce/services/rpc/similarproducts/internal/svc"
	"k8scommerce/services/rpc/similarproducts/pb/similarproducts"

	"github.com/localrivet/galaxycache"
)

type SimilarProductsClientServer struct {
	svcCtx   *svc.ServiceContext
	universe *galaxycache.Universe
}

func NewSimilarProductsClientServer(svcCtx *svc.ServiceContext, universe *galaxycache.Universe) *SimilarProductsClientServer {
	return &SimilarProductsClientServer{
		svcCtx:   svcCtx,
		universe: universe,
	}
}

func (s *SimilarProductsClientServer) GetSimilarProductsBySku(ctx context.Context, in *similarproducts.GetSimilarProductsBySkuRequest) (*similarproducts.GetSimilarProductsBySkuResponse, error) {
	l := logic.NewGetSimilarProductsBySkuLogic(ctx, s.svcCtx, s.universe)
	return l.GetSimilarProductsBySku(in)
}
