apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: grafana
resources:
- spec.yaml
configMapGenerator:
  - name: grafana-datasources
    files:
      - config/datasources.yaml
  - name: grafana-dashboards
    files:
      - dashboards/grpc.json
  - name: dashboard-config
    files:
      - config/dashboardConfig.yaml