// Code generated by goctl. DO NOT EDIT!
// Source: customer.proto

package server

import (
	"context"

	"k8scommerce/services/rpc/customer/internal/logic"
	"k8scommerce/services/rpc/customer/internal/svc"
	"k8scommerce/services/rpc/customer/pb/customer"
)

type CustomerClientServer struct {
	svcCtx *svc.ServiceContext
	customer.UnimplementedCustomerClientServer
}

func NewCustomerClientServer(svcCtx *svc.ServiceContext) *CustomerClientServer {
	return &CustomerClientServer{
		svcCtx: svcCtx,
	}
}

func (s *CustomerClientServer) CreateCustomer(ctx context.Context, in *customer.CreateCustomerRequest) (*customer.CreateCustomerResponse, error) {
	l := logic.NewCreateCustomerLogic(ctx, s.svcCtx)
	return l.CreateCustomer(in)
}

func (s *CustomerClientServer) Login(ctx context.Context, in *customer.LoginRequest) (*customer.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
