Name: shipping.rpc
Target: k8s://k8scommerce/shipping:8080
ListenOn: :8080
Log:
  Mode: console
Postgres:
  Connection: postgres://postgres:postgres@k8scommerce-db:5432/k8scommerce?connect_timeout=180&sslmode=disable
  MaxOpenConnections: 10
  MaxIdleConnections: 2
  MaxConnectionLifetimeMinutes: 5